project:
  type: website
  output-dir: docs

website:
  title: "Australiam Farm Dams"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: info.qmd
        text: Infographics
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

